#make file for assign1
stackArray: stackArray.o
	gcc stackArray.o -o stackArray
stackList: stackList.o
	gcc stackList.o -o stackList
queueArray: queueArray.o
	gcc queueArray.o -o queueArray
queueList: queueList.o -o queueList
	gcc queueList -o queueList

stackArray.o: stackArray.c
	gcc -c stackArray.c
stackList.o: stackList.c
	gcc -c stackList.c
queueArray.o: queueArray.c
	gcc -c queueArray.c
queueList.o: queueList.c
	gcc -c queueList.c

clean:
	rm *.o stackArray stackList queueArray queueList






